spectate-duration: 15
spectate-death-duration: 10
non-interruption-in-death-spectation: true
triggers:
  damage: true
  damage-threshold: 5.0
  hostile-mob-hit: true
  fall-damage-prediction: true
  fall-distance-threshold: 5.0
